// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BillsUIClient is the client API for BillsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillsUIClient interface {
	// ListEngineSpecs returns a list of Billing Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (BillsUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type billsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewBillsUIClient(cc grpc.ClientConnInterface) BillsUIClient {
	return &billsUIClient{cc}
}

func (c *billsUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (BillsUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BillsUI_ServiceDesc.Streams[0], "/v1.BillsUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &billsUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BillsUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type billsUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *billsUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *billsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.BillsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillsUIServer is the server API for BillsUI service.
// All implementations must embed UnimplementedBillsUIServer
// for forward compatibility
type BillsUIServer interface {
	// ListEngineSpecs returns a list of Billing Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, BillsUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedBillsUIServer()
}

// UnimplementedBillsUIServer must be embedded to have forward compatible implementations.
type UnimplementedBillsUIServer struct {
}

func (UnimplementedBillsUIServer) ListEngineSpecs(*ListEngineSpecsRequest, BillsUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedBillsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedBillsUIServer) mustEmbedUnimplementedBillsUIServer() {}

// UnsafeBillsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillsUIServer will
// result in compilation errors.
type UnsafeBillsUIServer interface {
	mustEmbedUnimplementedBillsUIServer()
}

func RegisterBillsUIServer(s grpc.ServiceRegistrar, srv BillsUIServer) {
	s.RegisterService(&BillsUI_ServiceDesc, srv)
}

func _BillsUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BillsUIServer).ListEngineSpecs(m, &billsUIListEngineSpecsServer{stream})
}

type BillsUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type billsUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *billsUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BillsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BillsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillsUI_ServiceDesc is the grpc.ServiceDesc for BillsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BillsUI",
	HandlerType: (*BillsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _BillsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _BillsUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bills-ui.proto",
}
